const countryAndCurrencyList = {
    BGN: { conCode: "BG", currName: "Bulgarian Lev" },
    BRL: { conCode: "BR", currName: "Brazilian Real" },
    NOK: { conCode: "BV", currName: "Norwegian Krone" },
    CAD: { conCode: "CA", currName: "Canadian Dollar" },
    CHF: { conCode: "CH", currName: "Swiss Franc" },
    CNY: { conCode: "CN", currName: "Chinese Yuan" },
    CZK: { conCode: "CZ", currName: "Czech Republic Koruna" },
    DKK: { conCode: "DK", currName: "Danish Krone" },
    EUR: { conCode: "FR", currName: "Euro" },
    GBP: { conCode: "GB", currName: "British Pound Sterling" },
    HKD: { conCode: "HK", currName: "Hong Kong Dollar" },
    HRK: { conCode: "HR", currName: "Croatian Kuna" },
    HUF: { conCode: "HU", currName: "Hungarian Forint" },
    IDR: { conCode: "ID", currName: "Indonesian Rupiah" },
    ILS: { conCode: "IL", currName: "Israeli New Sheqel" },
    INR: { conCode: "IN", currName: "Indian Rupee" },
    ISK: { conCode: "IS", currName: "Icelandic Króna" },
    JPY: { conCode: "JP", currName: "Japanese Yen" },
    KRW: { conCode: "KR", currName: "South Korean Won" },
    MXN: { conCode: "MX", currName: "Mexican Peso" },
    MYR: { conCode: "MY", currName: "Malaysian Ringgit" },
    NZD: { conCode: "NZ", currName: "New Zealand Dollar" },
    PHP: { conCode: "PH", currName: "Philippine Peso" },
    PLN: { conCode: "PL", currName: "Polish Zloty" },
    RON: { conCode: "RO", currName: "Romanian Leu" },
    RUB: { conCode: "RU", currName: "Russian Ruble" },
    SEK: { conCode: "SE", currName: "Swedish Krona" },
    SGD: { conCode: "SG", currName: "Singapore Dollar" },
    THB: { conCode: "TH", currName: "Thai Baht" },
    TRY: { conCode: "TR", currName: "Turkish Lira" },
    USD: { conCode: "US", currName: "US Dollar" },
    ZAR: { conCode: "ZA", currName: "South African Rand" },
}